package web

import (
	"log"
	"os"
	"strings"
)

// Router prompt slimming (plan 3.1).
//
// The tool-router turn answers with a JSON tool decision only; the user-facing
// answer is generated by a separate, untouched answer turn. Routing therefore
// does not need the full 93KB history that caused the 2026-09-08 metering
// storm — but it does depend on history for deictic inputs ("use the first
// tool from above"). The design is adaptive:
//
//   - baseline: the last RouterPromptTailMessages messages (system messages
//     always included) capped per the window byte budget, plus the ledger's
//     RouterContext tool-execution summary;
//   - automatic upgrade to the FULL flattened prompt whenever the recent
//     window contains reference/anaphora markers, so deictic routing keeps
//     working;
//   - small payloads are left untouched (nothing to save);
//   - M365_ROUTER_PROMPT_SLIMMING=false (or the admin settings toggle) reverts
//     to the legacy always-full behaviour.

const routerSlimmingMinPromptBytes = 8192

var routerReferenceHints = []string{
	// zh
	"上面", "上边", "之前", "先前", "刚才", "刚刚", "继续", "接着", "同样",
	"上一个", "前一个", "那个工具", "再试", "重试", "同上", "照旧", "还是用",
	// en
	"above", "previous", "earlier", "just now", "continue", "same as",
	"last one", "that one", "the first tool", "again", "retry",
}

// routerWindowMessages returns the message subset the slim route prompt is
// built from: every system/developer message plus the trailing tail of
// non-system messages. A window never begins with an orphan tool result: the
// start is walked back so the assistant tool_calls that produced it stay
// attached.
func routerWindowMessages(msgs []oaiMsg, tail int) []oaiMsg {
	if tail < 1 {
		tail = 1
	}
	var sys, rest []oaiMsg
	for _, m := range msgs {
		role := strings.ToLower(strings.TrimSpace(m.Role))
		if role == "system" || role == "developer" {
			sys = append(sys, m)
		} else {
			rest = append(rest, m)
		}
	}
	start := len(rest) - tail
	if start < 0 {
		start = 0
	}
	for start > 0 && strings.EqualFold(strings.TrimSpace(rest[start].Role), "tool") {
		start--
	}
	out := make([]oaiMsg, 0, len(sys)+len(rest)-start)
	out = append(out, sys...)
	out = append(out, rest[start:]...)
	return out
}

// routerWindowNeedsFullHistory reports whether the recent window contains
// deictic/reference markers, in which case routing quality depends on the
// older history and the full prompt is used.
//
// Only the most recent user message is scanned. Scanning every user message
// in the window made the upgrade fire on 72% of real agent requests (words
// like "continue"/"above" are ubiquitous in task instructions), erasing the
// slimming benefit. Deixis is inherently a property of the current turn; the
// ledger's tool evidence plus the tail window carry the rest.
func routerWindowNeedsFullHistory(window []oaiMsg) bool {
	latest := ""
	for _, m := range window {
		role := strings.ToLower(strings.TrimSpace(m.Role))
		if role != "user" {
			continue
		}
		if txt, _ := parseContent(m.Content); txt != "" {
			latest = txt
		}
	}
	low := strings.ToLower(latest)
	for _, hint := range routerReferenceHints {
		if strings.Contains(low, hint) {
			return true
		}
	}
	return false
}

// trimRouterWindowHead caps a flattened window at budget bytes, cutting from
// the oldest end at a message boundary. Order is oldest-first, so keeping the
// tail preserves the most recent — and for routing most relevant — turns.
func trimRouterWindowHead(s string, budget int) string {
	if budget <= 0 || len(s) <= budget {
		return s
	}
	cut := len(s) - budget
	if idx := strings.Index(s[cut:], "\n["); idx >= 0 {
		cut += idx
	} else {
		// Advance to a rune boundary to avoid splitting a multi-byte rune.
		for cut < len(s) && (s[cut]&0xC0) == 0x80 {
			cut++
		}
	}
	return "[earlier history trimmed for routing]\n" + s[cut:]
}

// buildRoutePrompt assembles the prompt for the synchronous tool-router turn.
// fullPrompt is the complete flattened history; answerPrompt may be an
// incremental resolver prompt. With slimming disabled this is byte-for-byte
// the legacy behaviour (answerPrompt-based).
func (s *Server) buildRoutePrompt(body *oaiReq, fullPrompt, answerPrompt string, ledger agentLedger, executionAnchor string, toolMaps []map[string]any) string {
	source := answerPrompt + "\n" + ledger.RouterContext()
	full := modelToolRouterPrompt(source, toolMaps, body.ToolChoice, executionAnchor)
	cfg := s.settings.get()
	if !cfg.RouterPromptSlimming {
		return full
	}
	if os.Getenv("M365_ROUTER_PROMPT_SLIMMING") == "false" {
		return full
	}
	// Nothing worth saving on small payloads; skip the behaviour change.
	if len(full) <= routerSlimmingMinPromptBytes {
		return full
	}
	window := routerWindowMessages(body.Messages, cfg.RouterPromptTailMessages)
	if routerWindowNeedsFullHistory(window) {
		log.Printf("[router-slim] upgrade_to_full reason=reference_hint prompt_len=%d", len(full))
		return modelToolRouterPrompt(fullPrompt+"\n"+ledger.RouterContext(), toolMaps, body.ToolChoice, executionAnchor)
	}
	budget := cfg.RouterPromptMaxBytes * (cfg.RouterPromptTailMessages + 1)
	flat, _ := flattenPromptMessages(window, nil)
	flat = trimRouterWindowHead(flat, budget)
	slim := modelToolRouterPrompt(flat+"\n"+ledger.RouterContext(), toolMaps, body.ToolChoice, executionAnchor)
	if len(slim) >= len(full) {
		// Slimming produced no saving (e.g. the ledger dominates); keep the
		// legacy prompt so routing sees strictly more context.
		return full
	}
	log.Printf("[router-slim] slimmed full=%d slim=%d tail=%d max_bytes=%d", len(full), len(slim), cfg.RouterPromptTailMessages, cfg.RouterPromptMaxBytes)
	return slim
}
